app/account/urls.py
from django.urls import path, include

from account.views import ProfileView, UserSignUpView, UserActivateView

app_name = 'account'


urlpatterns = [
    path('profile/', ProfileView.as_view(), name='profile'),
    path('signup/', UserSignUpView.as_view(), name='signup'),
    path('activate/<uuid:username>/', UserActivateView.as_view(), name='activate'),
]

app/currency/api/urls.py
from django.urls import path
from rest_framework import routers

from currency.api.views import RateViewSet

router = routers.SimpleRouter(trailing_slash=True)
router.register(r'rates', RateViewSet, basename='rate')

app_name = 'currency_api'

urlpatterns = [
    # path('rates/', RateListAPIView.as_view(), name='rate-list'),
    # path('rates/<int:pk>/', RateDetailsAPIView.as_view(), name='rate-details')
] + router.urls

app/currency/urls.py
from django.urls import path

from currency.views import (
    RateListView,
    RateCreateView,
    RateUpdateView,
    RateDeleteView,
    RateDetailView,
    ContactUsCreateView,
)

app_name = 'currency'


urlpatterns = [
    path('rate/list/', RateListView.as_view(), name='rate-list'),
    path('rate/create/', RateCreateView.as_view(), name='rate-create'),
    path('rate/update/<int:pk>/', RateUpdateView.as_view(), name='rate-update'),
    path('rate/delete/<int:pk>/', RateDeleteView.as_view(), name='rate-delete'),
    path('rate/details/<int:pk>/', RateDetailView.as_view(), name='rate-details'),

    path('contactus/create/', ContactUsCreateView.as_view(), name='contactus-create'),
]

app/settings/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

from currency.views import IndexView

schema_view = get_schema_view(
   openapi.Info(
      title="Currency API",
      default_version='v1',
      description="Test description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('admin/', admin.site.urls),

    path('auth/', include('django.contrib.auth.urls')),
    path('auth/', include('account.urls')),

    path('currency/', include('currency.urls')),

    path('api/currency/', include('currency.api.urls')),
    path('api/account/', include('account.api.urls')),

    path('__debug__/', include('debug_toolbar.urls')),

    path('', IndexView.as_view(), name='index'),

    path('swagger<format>/', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # url /media/... -> file system /media/

app/currency/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from currency.choices import CurrencyTypeChoices


class Rate(models.Model):
    buy = models.DecimalField(_('Buy'), max_digits=6, decimal_places=2)
    sell = models.DecimalField(_('Sell'), max_digits=6, decimal_places=2)
    created = models.DateTimeField(_('Created'), auto_now_add=True)
    currency_type = models.SmallIntegerField(
        _('Currency type'),
        choices=CurrencyTypeChoices.choices,
        # default=1, WRONG
        default=CurrencyTypeChoices.USD  # correct
        # if field contains choices, then human-readable format = get_<field_name>_display()
    )
    source = models.ForeignKey('currency.Source', on_delete=models.CASCADE, related_name='rates')

    class Meta:
        verbose_name = _('Rate')
        verbose_name_plural = _('Rates')

    def __str__(self):
        return f'{self.buy} - {self.sell}'


class Source(models.Model):
    '''
    One To One - X
    One To Many - V
    Many To Many - ~


    rate_set
    '''
    name = models.CharField(_('Source'), max_length=64)
    code_name = models.CharField(_('Code name'), max_length=64, unique=True)

    class Meta:
        verbose_name = _('Source')
        verbose_name_plural = _('Sources')

    def __str__(self):
        return self.name


class ContactUs(models.Model):
    created = models.DateTimeField(_('Created'), auto_now_add=True)
    name = models.CharField(_('Name'), max_length=64)
    email = models.EmailField(_('Email'), max_length=128)
    subject = models.CharField(_('Subject'), max_length=256)
    body = models.CharField(_('Body'), max_length=2048)

    class Meta:
        verbose_name = _('Contact Us')
        verbose_name_plural = _('Contact Us')

app/currency/forms.py
from django import forms

from currency.models import Rate, Source


class RateForm(forms.ModelForm):

    class Meta:
        model = Rate
        fields = (
            'buy',
            'sell',
            'currency_type',
            'source',
        )


class SourceForm(forms.ModelForm):
    class Meta:
        model = Source
        fields = (
            'name',
        )

app/currency/api/views.py
from django.core.cache import cache
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework.decorators import action
from rest_framework.filters import OrderingFilter
from rest_framework.permissions import AllowAny
from rest_framework.response import Response
from rest_framework.viewsets import ModelViewSet

from currency.api.paginators import RatePagination
from currency.api.serializers import RateSerializer
from currency.api.throtling import RateThrottle
from currency.choices import CurrencyTypeChoices
from currency.constants import LATEST_RATES_CACHE_KEY
from currency.filters import RateFilter
from currency.models import Rate, Source


# class RateListAPIView(ListCreateAPIView):
#     queryset = Rate.objects.all().order_by('-created')
#     serializer_class = RateSerializer  # json -> obj, obj -> json
#     renderer_classes = (JSONRenderer, XMLRenderer, YAMLRenderer)
#
#
# class RateDetailsAPIView(RetrieveUpdateDestroyAPIView):
#     queryset = Rate.objects.all().order_by('-created')
#     serializer_class = RateSerializer
#     renderer_classes = (JSONRenderer, XMLRenderer, YAMLRenderer)


class RateViewSet(ModelViewSet):
    queryset = Rate.objects.all().order_by('-created')
    serializer_class = RateSerializer  # json -> obj, obj -> json
    # renderer_classes = (JSONRenderer, XMLRenderer, YAMLRenderer)
    pagination_class = RatePagination
    filterset_class = RateFilter
    filter_backends = (
        DjangoFilterBackend,
        OrderingFilter,
    )
    ordering_fields = ('buy', 'sell', 'created')
    throttle_classes = (RateThrottle,)
    permission_classes = (AllowAny,)

    @action(methods=('GET',), detail=False, serializer_class=RateSerializer)
    def latest(self, request, *args, **kwargs):
        cached_data = cache.get(LATEST_RATES_CACHE_KEY)
        if cached_data is not None:
            return Response(cached_data)

        sources = Source.objects.all()

        latest_rates = []
        for source in sources:
            for currency in CurrencyTypeChoices:
                rate = Rate.objects.filter(source=source, currency_type=currency).order_by('-created').first()

                if rate is not None:
                    latest_rates.append(RateSerializer(instance=rate).data)

        cache.set(LATEST_RATES_CACHE_KEY, latest_rates, 60 * 60 * 24 * 7)  # 1 week

        return Response(latest_rates)

app/currency/views.py
import re
import json
from datetime import datetime, timedelta
from time import time

from django.views.generic import (
    CreateView, UpdateView,
    DeleteView, DetailView, TemplateView
)
from django_filters.views import FilterView
from django.urls import reverse_lazy
from rest_framework.decorators import api_view
from rest_framework.response import Response

from currency.filters import RateFilter
from currency.forms import RateForm
from currency.models import Rate, ContactUs
from currency.tasks import send_email_in_background


class RateListView(FilterView):
    queryset = Rate.objects.all().select_related('source').order_by('-created')
    template_name = 'rate_list.html'
    paginate_by = 30
    filterset_class = RateFilter

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)

        query_parameters = self.request.GET.urlencode()
        # context['filter_params'] = '&'.join(
        #     f'{key}={value}' for key, value in self.request.GET.items()
        #     if key != 'page'
        # )

        context['filter_params'] = re.sub(r'page=\d+', '', query_parameters).lstrip('&')

        return context


class RateCreateView(CreateView):
    form_class = RateForm
    success_url = reverse_lazy('currency:rate-list')
    template_name = 'rate_create.html'


class RateUpdateView(UpdateView):
    model = Rate
    form_class = RateForm
    success_url = reverse_lazy('currency:rate-list')
    template_name = 'rate_update.html'


class RateDeleteView(DeleteView):
    model = Rate
    success_url = reverse_lazy('currency:rate-list')
    template_name = 'rate_delete.html'


class RateDetailView(DetailView):
    model = Rate
    template_name = 'rate_detail.html'


class IndexView(TemplateView):
    template_name = 'index.html'


class ContactUsCreateView(CreateView):
    model = ContactUs
    template_name = 'contactus_create.html'
    success_url = reverse_lazy('index')
    fields = (
        'name',
        'email',
        'subject',
        'body',
    )

    def _send_email(self):
        '''
        | 00:00 - 07:59 | 08:00 - 17:59 | 18:00 - 23:59 |
        | eta - 8:00    |  now          | eta - 8:00 next day|
        '''
        # recipient = 'hileltest1234@gmail.com'
        # WRONG! from settings import settings
        from django.conf import settings
        recipient = settings.DEFAULT_FROM_EMAIL
        subject = 'User contact us'
        body = f'''
                Name: {self.object.name}
                Email: {self.object.email}
                Subject: {self.object.subject}
                Body: {self.object.body}
                '''
        eta = datetime.now() + timedelta(seconds=60)
        send_email_in_background.apply_async(
            kwargs={
                'subject': subject,
                'body': body
            }
        )

    def form_valid(self, form):
        redirect = super().form_valid(form)

        self._send_email()

        return redirect

app/currency/templates/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'index' %}">Currency</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'currency:rate-list' %}">Rates<span
                        class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'currency:contactus-create' %}">Contact Us</a>
            </li>
            {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'account:profile' %}">Profile</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'account:signup' %}">Sign Up</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Login</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>

app/currency/templates/includes/pagination.html
{#<div class="pagination">#}
{#    <span class="step-links">#}
{#        {% if page_obj.has_previous %}#}
{#            <a href="?page=1">&laquo; first</a>#}
{#            <a href="?page={{ page_obj.previous_page_number }}">previous</a>#}
{#        {% endif %}#}
{##}
{#        <span class="current">#}
{#            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.#}
{#        </span>#}
{##}
{#        {% if page_obj.has_next %}#}
{#            <a href="?page={{ page_obj.next_page_number }}">next</a>#}
{#            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>#}
{#        {% endif %}#}
{#    </span>#}
{#</div>#}


<nav aria-label="...">
  <ul class="pagination">
       {% if page_obj.has_previous %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page_obj.previous_page_number }}&{{ filter_params }}" tabindex="-1">Previous</a>
    </li>
      {% endif %}
    
  {% for page_number in page_obj.paginator.page_range %}
            {% if page_obj.number == page_number %}
                <li class="page-item active">
                    <a class="page-link" href="?page={{ page_number }}&{{ filter_params }}">{{ page_number }}<span class="sr-only">(current)</span></a>
                </li>
            {% else %}
                <li class="page-item">
                <a href="?page={{ page_number }}&{{ filter_params }}" class="page-link">
                    {{ page_number }}
                </a>
                </li>
            {% endif %}
        {% endfor %}
  
  {% if page_obj.has_next %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page_obj.next_page_number }}&{{ filter_params }}">Next</a>
    </li>
  {% endif %}
  </ul>
</nav>